name: Cypress Tests

on:
  pull_request:
  push:
    branches:
      - main
      - feat/9253-introduce-cypress-e2e-integration-tests

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CYPRESS_CONTAINER_REGISTRY_TOKEN }}

      - name: Build and run dev container task
        uses: devcontainers/ci@v0.3
        with:
        imageName: ghcr.io/${{ env.DOCKER_NAMESPACE }}/${{ env.DEVCONTAINER_IMAGE_NAME }}
        cacheFrom: ghcr.io/${{ env.DOCKER_NAMESPACE }}/${{ env.DEVCONTAINER_IMAGE_NAME }}
        push: always
          runCmd: cd web && yarn test:e2e:ci

      - name: Upload Cypress videos
        uses: actions/upload-artifact@v3
        with:
          name: cypress-videos
          path: web/cypress/videos/**/*.mp4
        if: always()
      
      - name: Upload Cypress screenshots
        uses: actions/upload-artifact@v3
        with:
          name: cypress-screenshots
          path: web/cypress/screenshots/**/*.png
        if: always()
